# Generated by Django 5.2.5 on 2025-09-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do cliente.', max_length=100)),
                ('data_nascimento', models.DateField(help_text='Data de nascimento (DD/MM/AAAA).')),
                ('hora_nascimento', models.TimeField(help_text='Hora de nascimento (HH:MM).')),
                ('local_nascimento', models.CharField(help_text='Cidade, estado e país de nascimento (ex: São Paulo, SP, Brasil).', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
